# Generated by Django 2.0.2 on 2018-03-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_amount', models.FloatField()),
                ('trans_date', models.DateField()),
                ('trans_type', models.CharField(max_length=1)),
                ('trans_remarks', models.CharField(max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Account')),
            ],
        ),
    ]
